apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Bump Public Action Images

on:
  push:
    branches:
      - master

permissions:
  scm-token-own: read

jobs:
  bump-actions:
    if: ${{ cloudbees.scm.branch == 'master' }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v2
        with:
          fetch-depth: 2

      - name: Check if action_artifacts.json changed
        id: check-changes
        uses: docker://alpine/git:latest
        run: |
          echo "changed=false" >> $CLOUDBEES_OUTPUTS/result
          echo "Inside"
          echo "set"
          echo ${{ steps.check-changes.outputs.result }}
      - name: Bump all changed actions
        if: ${{ steps.check-changes.outputs.result == 'changed=true' }}
        uses: docker://alpine:latest
        run: |
          echo 'inside'
